# Generated by Django 3.1.7 on 2021-05-02 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=100, verbose_name='House/Flat #')),
                ('area', models.CharField(max_length=100, verbose_name='Area')),
                ('landmark', models.CharField(max_length=100, verbose_name='Landmark')),
                ('pincode', models.CharField(max_length=6, verbose_name='Pincode')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
