# Generated by Django 3.1.7 on 2021-05-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210502_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='category',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('Other', 'Other')], default='Home', max_length=20),
        ),
        migrations.DeleteModel(
            name='AddressCategory',
        ),
    ]
