# Generated by Django 3.1.7 on 2021-05-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customeraddress_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='category_string',
            field=models.CharField(default='Alias', max_length=20, verbose_name='Alias'),
        ),
    ]
