# Generated by Django 3.1.7 on 2021-05-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210509_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='Phone Number'),
        ),
    ]
