# Generated by Django 3.1.7 on 2021-05-02 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 2, 16, 47, 32, 150360)),
        ),
    ]
