# Generated by Django 3.1.7 on 2021-05-03 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20210503_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancelled_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 4, 4, 24, 57, 586718)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.DateField(default=datetime.date(2021, 5, 5), verbose_name='Delivery Date'),
        ),
    ]
