# Generated by Django 3.1.7 on 2021-05-04 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20210504_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.CharField(default='', max_length=50, verbose_name='Cooking Instructions'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancelled_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 4, 6, 18, 11, 758515)),
        ),
    ]
