# Generated by Django 3.1.7 on 2021-05-08 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20210507_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancelled_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 9, 4, 1, 53, 398552)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.DateField(default=datetime.date(2021, 5, 9), verbose_name='Delivery Date'),
        ),
    ]
