# Generated by Django 3.1.7 on 2021-05-08 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20210509_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='main_category',
        ),
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.CharField(choices=[('Sweet', 'Sweet'), ('Savoury', 'Savoury')], default='Sweet', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancelled_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 9, 4, 35, 0, 373898)),
        ),
    ]
