# Generated by Django 3.1.7 on 2021-05-09 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_auto_20210509_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancelled_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 9, 19, 49, 37, 592869)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.DateField(default=datetime.date(2021, 5, 10), verbose_name='Delivery Date'),
        ),
    ]
