# Generated by Django 3.1.7 on 2021-05-09 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_auto_20210509_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancelled_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 9, 23, 50, 34, 905603)),
        ),
    ]
