# Generated by Django 3.1.7 on 2021-05-10 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_auto_20210511_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancelled_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 11, 1, 0, 31, 408294)),
        ),
    ]
