# Generated by Django 3.1.7 on 2021-05-12 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_auto_20210511_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancelled_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 13, 3, 7, 57, 244545)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.DateField(default=datetime.date(2021, 5, 14), verbose_name='Delivery Date'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
