# Generated by Django 3.1.7 on 2021-05-12 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_auto_20210513_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancelled_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 13, 3, 15, 22, 457274)),
        ),
    ]
