# Generated by Django 3.1.7 on 2021-05-12 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_auto_20210513_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancelled_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 13, 3, 32, 52, 63253)),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
